### ISSUE TITLE
How can hold bitcoin ?

### ISSUE THREAD

**Issue by gunjanbacancy** [mehdibo/Codeigniter-blockchain#2]
Hi,
How can I hold bitcoin ?
Any API provide by blockchain for that ?
Thanks.

**Comment by mehdibo** [comment]
What do you mean by hold?

**Comment by gunjanbacancy** [comment]
I am working with BTC transaction on my web platform and it's working fine and for security concern i am stuck at a point and like to discuss with you. So, my stuff is something like following;

There are 2 sides of my web platform ie (i) Front side and (ii) Admin side.

Now, i want to implement something like whenever any frontend user submit a request to transfer "X" BTC amount to "SOME_ADDRESS", so, that i want to build a secure connection like whenever admin found his requests satisfies all the normal criteria , he will approve this request and transferring funds actual takes place by blockchain.

So, mean while i want to build something like until and unless admin approves/reject the request till that time i want to freeze that BTC amount from user's account.

So, is there any API available to implement such things ?

**Comment by mehdibo** [comment]
No you can't do so, unless you want to transfer it to a wallet that holds the money until you approve it and then re send it
