### ISSUE TITLE
hi mehdibo

### ISSUE THREAD

**Issue by ercanakca** [mehdibo/Codeigniter-blockchain#3]
I am coding Codeigniter 3.x project.
I need to use the blockchain API.
composer, npm, nodejs and blockchain-wallet-service.
but I want to test the API on nu line

`$ Blockchain = new \ Blockchain \ Blockchain ();`

I'm getting an error.

"Message: Class 'Blockchain \ Blockchain' not found"
what could be the problem?

**Comment by mehdibo** [comment]
Did you define a namespace called Blockchain?

**Comment by ercanakca** [comment]
Yes, i'm tried. 
I even tried laravel.
[https://github.com/blockchain/api-v1-client-php](url)
I will share a video about this error.

**Comment by mehdibo** [comment]
I'm not sure what are you trying to do, but to load the library you need to do
`$this->load->library('blockchain' , $config)`
More details here:
https://github.com/mehdibo/Codeigniter-blockchain#documentation

**Comment by tarunbraintreee** [comment]
Hello I am facing issue
 Blockchain: Unable to connect to Blockchain Wallet service on: http://127.0.0.1:3000
plz help me

**Comment by mehdibo** [comment]
@tarunbraintreee Please open a new issue
