### ISSUE TITLE
error: Unknown Wallet Identifier. Please check you entered it correctly.

### ISSUE THREAD

**Issue by Michelgard** [mehdibo/Codeigniter-blockchain#5]
### Errors
Hello,
I always have the same error in the console:
- error: Unknown Wallet Identifier. Please check you entered it correctly.

### Method's returned value
Yet I have several times to check my data.
Here is my request:
  wget 'http: //127.0.0.1: 3000 / merchant / xpub ....
      ........ CDHBp / balance /? Password = my-Password '

Connexion à 127.0.0.1:3000… connecté.
requête HTTP transmise, en attente de la réponse… 500 Internal Server Error
2018-12-15 10:33:57 erreur 500 : Internal Server Error.

### Extra details
I think my intallation is OK I added JDK.
I do not understand !

**Comment by Michelgard** [comment]
Okay!
Just a code error between xPub and the identifier

**Comment by jaslam94** [comment]
Can you please explain the code solution in a bit of detail? I am facing the same error.

**Comment by techyroots** [comment]
Hello, is there any solution for this error? I am facing the same error.
